modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="pandora"
version="1.0.0"
displayName="Pandora"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="kiera, MCreator"

[[dependencies.pandora]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



